# Generated by Django 4.1.2 on 2022-10-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="ownerId",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="slot", name="desc", field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="slot", name="slot", field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="slot", name="status", field=models.CharField(max_length=20),
        ),
    ]
